# Generated by Django 4.1.4 on 2022-12-30 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Employeeid', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=55)),
                ('Email', models.EmailField(max_length=55)),
                ('Password', models.CharField(max_length=55)),
                ('Designation', models.CharField(choices=[('Android Developer', 'android developer'), ('Backend Developer)', 'backend developer)')], max_length=44)),
            ],
        ),
    ]
