# Generated by Django 4.1.4 on 2023-01-02 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprojectapp', '0002_alter_employee_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employeesignin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Employeeid',
            new_name='Empid',
        ),
    ]
