# Generated by Django 4.1.4 on 2023-01-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprojectapp', '0003_employeesignin_rename_employeeid_employee_empid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Empid', models.IntegerField()),
                ('Name', models.CharField(max_length=55)),
                ('Email', models.EmailField(max_length=55)),
                ('Password', models.CharField(max_length=55)),
                ('Designation', models.CharField(choices=[('android developer', 'Android Developer'), ('backend developer)', 'Backend Developer')], max_length=44)),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Employeesignin',
        ),
    ]
